# Monthly Report: {{MONTH}}

## Executive Summary

**Project**: {{PROJECT_NAME}}
**Period**: {{START_DATE}} ~ {{END_DATE}}

{{EXECUTIVE_SUMMARY}}

---

## Milestone Progress

| Milestone | Status | Progress | Tasks |
|-----------|--------|----------|-------|
{{MILESTONE_TABLE}}

## Velocity Trend

```
{{VELOCITY_CHART}}
```

**Average Velocity**: {{AVG_VELOCITY}} tasks/day
**Trend**: {{VELOCITY_TREND}}

---

## Accomplishments

### Major Completions

{{MAJOR_COMPLETIONS}}

### Key Decisions

{{KEY_DECISIONS}}

---

## Challenges & Blockers

{{CHALLENGES}}

## Lessons Learned

{{LESSONS_LEARNED}}

---

## Code Activity Summary

### Monthly Statistics

| Metric | Value |
|--------|-------|
| Total Commits | {{COMMIT_COUNT}} |
| Files Changed | {{FILES_CHANGED}} |
| Lines Added | +{{INSERTIONS}} |
| Lines Removed | -{{DELETIONS}} |
| Net Change | {{NET_CHANGE}} |

### Most Active Areas

{{ACTIVE_AREAS}}

### Contributor Summary

{{CONTRIBUTORS}}

---

## Next Month Plan

### Goals

{{NEXT_MONTH_GOALS}}

### Priorities

{{PRIORITIES}}

### Risks to Monitor

{{RISKS}}

---

## Appendix

### Detailed Task List

{{TASK_DETAILS}}

---

*Generated by PM Plugin Analytics*
