# Weekly Report: {{WEEK}}

## Overview

**Project**: {{PROJECT_NAME}}
**Period**: {{START_DATE}} ~ {{END_DATE}}
**Milestone**: {{CURRENT_MILESTONE}}

---

## Progress Summary

| Metric | Value |
|--------|-------|
| Tasks Completed | {{COMPLETED_COUNT}} |
| Tasks Remaining | {{REMAINING_COUNT}} |
| Progress | {{PROGRESS_PERCENT}}% |
| Velocity | {{VELOCITY}} tasks/day |

## Burndown Status

```
{{BURNDOWN_CHART}}
```

**Status**: {{BURNDOWN_STATUS}}

---

## Completed This Week

{{COMPLETED_TASKS}}

## Planned for Next Week

{{NEXT_WEEK_TASKS}}

## Blockers & Risks

{{BLOCKERS}}

---

## Code Activity

### Statistics

- Total Commits: {{COMMIT_COUNT}}
- Files Changed: {{FILES_CHANGED}}
- Lines Added: +{{INSERTIONS}}
- Lines Removed: -{{DELETIONS}}

### Hotspots

{{HOTSPOTS}}

### Contributors

{{CONTRIBUTORS}}

---

## Notes & Decisions

{{NOTES}}

---

*Generated by PM Plugin Analytics*
